name: 'deploy-lambda'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_FOR_DEPLOY_LAMBDA }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.8

      - env:
          AWS_REGION: ap-south-1
        run: |
          yarn install --frozen-lockfile
          ./deploy-lambda.sh
