name: 'sync-github-project-issues'

on:
  workflow_dispatch:

permissions:
  repository-projects: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # The bulk of the work is started from the make command, so that it's easier to invoke from a developer's machine, not just CI.
      - run: |
          yarn install --frozen-lockfile
          make sync-github-project-issues
        env:
          GITHUB_TOKEN_FOR_SYNC_PROJECTS: ${{ github.token }}
