name: 'sync-contributors'

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - env:
          GITHUB_TOKEN_FOR_CONTRIBUTORS: ${{ secrets.TOKEN_FOR_SYNC_CONTRIBUTORS }}
        run: |
          yarn run ts-node "src/sync-contributors.ts"
