name: 'sync-github-project-issues'

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - env:
          GITHUB_TOKEN_FOR_SYNC_PROJECTS: ${{ secrets.TOKEN_FOR_SYNC_PROJECTS }}
        run: |
          yarn run ts-node "src/sync-github-project-issues.ts" "DevOps Pod"
