name: 'sync-contributors'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - env:
          GITHUB_TOKEN_FOR_CONTRIBUTORS: ${{ secrets.TOKEN_FOR_SYNC_CONTRIBUTORS }}
        run: |
          yarn run ts-node "src/sync-contributors.ts"
