name: 'sync-github-project-issues'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - env:
          GITHUB_TOKEN_FOR_SYNC_PROJECTS: ${{ secrets.TOKEN_FOR_SYNC_PROJECTS }}
        run: |
          yarn run ts-node "src/sync-github-project-issues.ts"
